version: 1.0.0-alpha {build}

branches:
  only:
  - master
  - develop

configuration:
- Debug
- Release

platform: Any CPU

install:
- ps: >-
    Add-Type -AssemblyName System.IO.Compression.FileSystem
      (New-Object System.Net.WebClient).DownloadFile(
        'https://github.com/dokan-dev/dokany/releases/download/v0.8.0/DokanInstall_0.8.0_redist.exe',
        'C:\projects\dokancloudfs\DokanInstall.exe'
      )

before_build:
- cmd: nuget restore

build:
  project: DokanCloudFS.sln
  verbosity: normal

before_test:
- cmd: C:\projects\dokancloudfs\DokanInstall.exe /S

test:
  categories:
    except:
    - Online
